[package]
name = "engine-generic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
saiwork-core.workspace = true
saiwork-events.workspace = true
saiwork-process.workspace = true
saiwork-diagnostics.workspace = true
async-trait = "0.1"
serde.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
engine-fake.workspace = true
saiwork-process = { workspace = true, features = ["failpoints"] }
